#!/usr/bin/env bash

set -Eeuo pipefail

[[ "${1:-}" == "ssm" && "${2:-}" == "get-parameter" ]] || exit 64
shift 2

parameter=""
while (( $# > 0 )); do
  case "$1" in
    --name)
      parameter="$2"
      shift 2
      ;;
    --with-decryption)
      shift
      ;;
    --query | --output)
      shift 2
      ;;
    *)
      exit 64
      ;;
  esac
done

[[ -n "${parameter}" ]] || exit 64
printf '%s\n' "${parameter}" >>"${FAKE_AWS_SSM_LOG:?}"
[[ "${parameter}" != "${FAKE_AWS_SSM_MISSING:-}" ]] || exit 254
printf '%s\n' "${parameter}"
